CloneBlog/CloneBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storm.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/',include('user.urls')),
]

if settings.DEBUG:
    # Test Mode
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CloneBlog/storm/urls.py
# from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'storm'

urlpatterns = [
    path('', views.IndexView.as_view(template_name='index_main.html'), name='index'),
    # path('nav/', views.IndexView.as_view(template_name='index_main.html'), name='shownav'),
    re_path('category/(?P<bigslug>.*?)/(?P<slug>.*?)', views.IndexView.as_view(), name='category'), 
    path('date/<int:year>/<int:month>/', views.IndexView.as_view(), name='date'),
    path('tag/<slug:tag>/', views.IndexView.as_view(), name='tag'),
    path('article/<slug:slug>/', views.ArticleView.as_view(), name='article'),
    path('love/',views.LoveView, name='loves')
]

CloneBlog/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.loginView , name='login'),
    path('logout/', views.logoutView , name='logout'),
    path('register/', views.registerView, name='register'),
    path('profile/', views.profileView, name='profile'),
    path('profile/change/', views.changeProfileView, name='change_profile'),
]

CloneBlog/storm/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from django.shortcuts import reverse
from django.utils import timezone

import markdown
import re

# 关键词
class Keyword(models.Model):
    name = models.CharField('文章关键词',max_length=20)

    class Meta:
        verbose_name = '关键词'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240, default=settings.SITE_DESCRIPTION,
                    help_text='用来作为SEO中的description, 长度参考SEO标准')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'tag': self.name})

    def get_article_list(self):
        return Article.objects.filter(tags=self)

# 网站导航菜单栏分类表
class BigCategory(models.Model):
    name = models.CharField('导航栏大分类', max_length=20)

    # 用作文章的访问路径  **/category/**
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
        default=settings.SITE_DESCRIPTION,
        help_text='用来作为SEO中的description, 长度参考SEO标准'
    )
    keywords = models.TextField('关键字', max_length=240, 
        default=settings.SITE_KEYWORDS,
        help_text='用来作为SEO中的keywords, 长度参考SEO标准'
    )

    class Meta:
        verbose_name = '导航栏分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 导航栏，分类下的下拉擦菜单分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
        default=settings.SITE_DESCRIPTION,
        help_text='用来作为SEO中的description, 长度参考SEO标准'
    )
    bigcategory = models.ForeignKey(BigCategory, verbose_name='大分类', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category',
                kwargs={'slug': self.slug, 'bigslug': self.bigcategory.slug}
        )

    def get_article_list(self):
        return Article.objects.filter(category=self)

# 文章
class Article(models.Model):
    IMG_LINK = '/static/images/summary.jpg'

    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField(max_length=240, verbose_name='文章摘要', 
                    default='文章摘要等同于网页description内容，请务必填写...'    )
    body = models.TextField(verbose_name='文章内容')
    img_link = models.CharField(verbose_name='图片地址', default=IMG_LINK, max_length=255)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField(verbose_name='阅读量', default=0)
    loves = models.IntegerField(verbose_name='喜欢量', default=0)

    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签' )
    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键字',
                help_text='文章关键字，用来作为SEO中keywords，最好使用长尾词，3-4个足够')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]

    def get_absolute_url(self):
        return reverse('storm:article', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.update_date = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        if not self.summary:
            self.summary = strip_tags(md.convert(self.body))[:50]
        super().save(*args, **kwargs)

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()

# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题', max_length=20, blank=True, null=True, help_text='标题可以为空'    )
    content = models.CharField('描述', max_length=80)
    img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接', max_length=200, default='#', help_text='图片跳转的超链接，默认#为不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        # 编号越小越靠前， 添加时间越晚越靠前
        ordering = ['number', '-id']

    def __str__(self):
        return self.content[:25]

# 公告
class Activate(models.Model):
    text = models.TextField('公告', null=True)
    is_active = models.BooleanField('是否开启', default=False)
    add_date = models.DateTimeField('提交日期', auto_now_add=True)

    class Meta:
        verbose_name = '公告'
        verbose_name_plural=verbose_name

    def __str__(self):
        return str(self.id) 


class FriendLink(models.Model):
    name = models.CharField('网站名字', max_length=50)
    description = models.CharField('网站描述', max_length=100, blank=True)
    link = models.URLField('友链地址', help_text='请填写http或https开头的完整形式地址')
    logo = models.URLField('友站LOGO', help_text='请填写http或https开头的完整形式地址', blank=True)
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    is_active = models.BooleanField('是否有效', default=True)
    is_show = models.BooleanField('是否首页展示', default=False)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.name
    
    def get_home_url(self):
        ''' 提取友链主页'''
        u = re.findall(r'(http|https://.*?)/.*?', self.link)
        home_url = u[0] if u else self.link
        return  home_url

    def active_to_false(self):
        self.is_active = False
        self.save(update_fields=['is_active'])

    def show_to_false(self):
        self.is_show = False
        self.save(update_fields=['is_show']) 

CloneBlog/storm/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse
# Create your views here.
from .models import Article, BigCategory, Category, Tag
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
import time, markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify

class HomePageView(TemplateView):
    template_name = 'index_main.html'

class IndexView(ListView):
    ''' 首页视图， 用于展示从数据库中获取的文章列表 '''
    #指定数据来源
    model = Article

    # template_name 属性用于指定所使用的 模板

    #指定 返回给模板中使用的 上下文变量名称， 表示文章列表
    context_object_name = 'articles'


    def get_queryset(self):
        ''' get_queryset函数： 返回用于检索该视图将要展示的对象的 数据集合 '''
        
        # 先调用父类的方法，获取 数据集合
        queryset = super(IndexView, self).get_queryset()

        # 提取 url路由 传入的参数
            # 归档日期
        year = self.kwargs.get('year', 0)
        month = self.kwargs.get('month', 0)
            # 标签
        tag = self.kwargs.get('tag', 0)

            # 导航栏
        self.big_slug = self.kwargs.get('big_slug', '')
            # 文章分类
        slug = self.kwargs.get('slug', '')

        # 按类型查询
        if self.big_slug:
            # 如果url中传入了 导航分类big_slug， 筛选出属于该分类的部分文章
            big = get_object_or_404(BigCategory, slug=self.big_slug)
            queryset = queryset.filter(category__bigcategory=big)
            
            if slug:
                # 如果 同时传入了 文章分类slug, 则再筛选出该分类下的文章
                slu = get_object_or_404(Category, slug=slug)
                queryset = queryset.filter(category=slu)

        # 按日期查询
        if year and month:
            queryset = get_list_or_404(queryset, create_date__year=year, create_date__month=month)

        # 按标签查询
        if tag:
            tags = get_object_or_404(Tag, name=tag)
            queryset = queryset.filter(tags=tags)
            self.big_slug = BigCategory.objects.filter(category__article__tags=tags)
            self.big_slug = self.big_slug[0].slug
        
        return queryset

    def get_context_data(self, **kwargs):
        ''' 返回用于显示对象列表的上下文数据 
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。    
        '''
        context = super(IndexView,self).get_context_data(**kwargs)
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。

        paginator = context.get('paginator')
        page = context.get('page')
        is_paginated = context.get('is_paginated')

        #返回的是一个字典
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        context.update(pagination_data)

        context['category'] = self.big_slug

        return context

    def pagination_data(self, paginator, page_obj, is_paginated):
        if not is_paginated:
            # 如果没有分页
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more=True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more=True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class ArticleView(DetailView):
    '''
        Django有基于类的视图DetailView,用于显示一个对象的详情页，我们继承它
    '''
    
    model = Article

    template_name = 'article.html'    

    context_object_name = 'article'

    def get_object(self):
        obj = super(ArticleView, self).get_object()

    # 设置浏览量增加时间判断,同一篇文章两次浏览超过半小时才重新统计阅览量,作者浏览忽略
        u = self.request.user
        ses = self.request.session
        # print(u, ses)
        the_key = 'is_read_{}'.format(obj.id)
        is_read_time = ses.get(the_key)

        if u != obj.author:
            if not is_read_time:
                obj.update_views()
                ses[the_key] = time.time()
            else:
                now_time = time.time()
                t = now_time - is_read_time
                if t > 60 *30:
                    obj.update_views()
                    ses[the_key] = now_time
        
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),    
        ])

        obj.body = md.convert(obj.body)
        obj.toc = md.toc
        return obj

    def get_context_data(self, **kwargs):
        context = super(ArticleView, self).get_context_data(**kwargs)
        context['category'] = self.object.id
        return context


@csrf_exempt
def LoveView(request):
    data_id = request.POST.get('um_id', '')
    if data_id:
        art = Article.objects.get(id=data_id)
        art.loves += 1
        art.save()
        return HttpResponse(art.loves)
    else:
        return HttpResponse('error', status=405)

CloneBlog/storm/templates/storm/inclusions/_article_list.html
{% for article in articles %}
<article class="excerpt">
    <header>
        <a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/
        {{ article.category.name|lower }}">{{ article.category.name }}<i class="label-arrow"></i></a>
        <h2>
            <a target="_blank" href="{{ article.get_absolute_url }}" title="{{ article.title }}">{{ article.title }}</a>
        </h2>
    </header>
    <div class="focus"><a target="_blank" href="{{ article.get_absolute_url }}">
        <img class="thumb" width="200px" height="123px" src="{{ article.img_link }}" alt="{{ article.title }}" /></a>
    </div>
        <span class="note"> {{ article.summary }}</span>
    <p class="auth-span">
        <span class="muted">
            <i class="fa fa-user"></i> <a href="#">{{ article.author }}</a>
        </span>
        <span class="muted">
            <i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d' }}
        </span>	
        <span class="muted">
            <i class="fa fa-eye"></i> {{ article.views }}
        </span>	
        <span class="muted">
            <i class="fa fa-comments-o"></i> 
            <a target="_blank" href="https://cuiqingcai.com/6408.html#comments">152评论</a>
        </span>
        <span class="muted">
            <a href="javascript:;" data-action="ding" data-id="6408" id="Addlike" class="action">
                <i class="fa fa-heart-o"></i><span class="count">{{ article.loves }}</span>喜欢
            </a>
        </span>
    </p>
</article>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}

CloneBlog/storm/templates/storm/inclusions/_carousel_images.html
<div class="ws_images">
    <ul>
        {% for carousel in carousels %}
        <li>
            <a target="_blank" href="{{ carousel.url }}" title="{{ carousel.content }}">
            <img src="{{ carousel.img_url }}" title="{{ carousel.content }}" alt="{{ carousel.title }}" />
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="ws_thumbs">
    <div>
        {% for carousel in carousels %}
        <a target="_blank" href="#" title="{{ carousel.title }}"><img src="{{ carousel.img_url }}" /></a>
        {% endfor %}
    </div>
</div>

CloneBlog/storm/templates/storm/inclusions/_carousel_right.html
<div id='metaslider_2698' class='nivoSlider'>
    {% for carousel in carousels %}
    <a href="{{ carousel.url }} " target="_blank">
        <img src="{{ carousel.img_url }}" height="300" width="320"
         data-title="{{ carousel.content }}" title="{{ carousel.title }}" 
         alt="{{ carousel.title }}" class="slider-2698 slide-1720" />
    </a>
    {% endfor %}
</div>

CloneBlog/storm/templates/storm/inclusions/_category_date.html
<ul>
    {% for article_date in article_dates %}
    <li><a href="{% url 'storm:date' article_date|date:'Y' article_date|date:'m' %}">{{ article_date|date:'Y-m' }}</a></li>
    {% empty %}
    <div>近期没有发布文章</div>
    {% endfor %}
</ul>

CloneBlog/storm/templates/storm/inclusions/_friend_link.html
<ul class='xoxo blogroll'>
    {% for flink in friendlinks %}
    <li><a href="{{ flink.link }}" target="_blank">{{ flink.name }}</a></li>
    {% empty %}
    <div>&nbsp;&nbsp;暂时没有友情链接</div>
    {% endfor %}
</ul>

CloneBlog/storm/templates/storm/inclusions/_hot_articles.html
<ul>
    {% for article in hot_articles %}
    <li>
        <p>	<span class="muted">
            <i class="fa fa-eye"></i><span class="count">{{ article.views }} </span> 浏览
            
            </span>
        </p>
        <span class="label label-1">{{ forloop.counter}}</span>
        <a href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>

CloneBlog/storm/templates/storm/inclusions/_list.html
{% load storm_tags %}
<div>
    <h3>显示inclusion_tag内容</h3>
    <ul>
        <b style="color: yellowgreen;">{{ showlists[0] }} </b>
        {% for i in showlists %}
        <li>
            <span>{{ i }} </span> <strong style="color: aqua;"> {% print_num i %} </strong>
        </li>
        {% empty %}
            暂无数据！
        {% endfor %}
    </ul>
</div>

CloneBlog/storm/templates/storm/inclusions/_love_articles.html
<ul>

    <li>
        <a href="https://cuiqingcai.com/1076.html" title="Python爬虫实战五之模拟登录淘宝并获取所有订单" >
            <span class="thumbnail">
                <img src="../static/images/timthumb.php" alt="Python爬虫实战五之模拟登录淘宝并获取所有订单" />
            </span>
            <span class="text">Python爬虫实战五之模拟登录淘宝并获取所有订单</span>
            <span class="muted">2015-02-24</span>
            <span class="muted">8,059评论</span>
        </a>
    </li>

</ul>

CloneBlog/storm/templates/storm/inclusions/_nav.html
{% load storm_tags %}
<li id="menu-item-44" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-44">
    <a href="/">首页</a>
</li>

<!-- 导航栏一级分类渲染 -->
{% for big in bigcategory %}
    <!-- 导航栏二级分类信息查询 -->

    {% get_category_list big as cate%}
    
    {% if cate %}
    <li id="menu-item-14" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-14">
        <a href="{% url 'storm:category' big.slug '' %}">{{ big.name}} </a>
        <ul class="sub-menu">
            <!-- 导航栏二级分类渲染 -->
            {% for c in cate %}
            <li id="menu-item-19" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-19">
                <a href="{% url 'storm:category' big.slug c.slug %}">{{ c.name}} </a>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% else %}
    <li id="menu-item-851" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-851">
        <a href="{% url 'storm:category' big.slug '' %}">{{ big.name}} </a>
    </li>
    {% endif %}
{% empty %}

{% endfor %}
<!--导航条结束-->

<!--搜索框-->
<li style="float:right;">
    <div class="toggle-search"><i class="fa fa-search"></i></div>
    <div class="search-expand" style="display: none;">
        <div class="search-expand-inner">
            <form method="get" class="searchform themeform" 
                onsubmit="location.href='https://cuiqingcai.com/?s=' + encodeURIComponent(this.s.value).replace(/%20/g, '+'); return false;" 
                action="/">
                <div> 
                    <input type="ext" class="search" name="s" 
                        onblur="if(this.value=='')this.value='search...';" 
                        onfocus="if(this.value=='search...')this.value='';" 
                        value="search...">
                </div>
            </form>
        </div>
    </div>
</li>
<!--搜索框-->

CloneBlog/storm/templates/storm/inclusions/_tag_list.html
<div class="d_tags">
    {% for tag in tag_lists %}
    <a title="{{ tag.total_num }}个话题" href="/tag/{{ tag.slug }}">{{ tag.name}} ({{ tag.total_num }})</a>
    {% empty %}
    <div>还没有设置标签</div>
    {% endfor %}
</div>