CloneBlog/CloneBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storm.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/',include('user.urls')),
]

if settings.DEBUG:
    # Test Mode
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CloneBlog/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.loginView , name='login'),
    path('logout/', views.logoutView , name='logout'),
    path('register/', views.registerView, name='register'),
    path('profile/', views.profileView, name='profile'),
    path('profile/change/', views.changeProfileView, name='change_profile'),
]

CloneBlog/user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class Ouser(AbstractUser):
    #继承至AbsotractUser （Django自带用户基类）

    # 拓展用户个人网站地址字段
    link = models.URLField('个人网站', blank=True, help_text='提示：网址必须填写以http开头的完整形式')

    # 拓展用户头像字段
    avatar = ProcessedImageField(
        upload_to = 'avatar/%Y/%m/%d',
        default='avatar/default.png',
        verbose_name='头像',
        processors=[ResizeToFill(80,80)]
    )

    class Meta:
        verbose_name='用户'
        verbose_name_plural=verbose_name
        ordering=['-id']

    def __str__(self):
        return self.username
        

CloneBlog/templates/oauth/change_profile.html
{%extends 'account/base.html' %}
{% load staticfiles %}
{% load oauth_tags %}

{% block title %}
<title>个人中心</title>
{% endblock %}


<!--主要内容块-->
{% block main %}
<main>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card rounded-0 px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>
                <div class="card-body">
                    <form action="{% url 'user:change_profile' %}" method="POST" class="change_profile" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% get_user_data request.session.uid as user %}
                        <div id="div_id_link" class="form-group">
                            <label for="id_link" class="form-control-label ">个人网址</label>
                            <div class="">
                                <input type="url" name="link" maxlength="200" class="urlinput form-control" id="id_link" />
                                <small id="hint_id_link" class="text-muted">提示：网址必须填写以http开头的完整形式</small>
                            </div>
                        </div>
                        
                        <div id="div_id_avatar" class="form-group">
                            <label for="id_avatar" class="form-control-label requiredField">
                                头像<span class="asteriskField">*</span>
                            </label>
                            <div class="">
                                目前：<a href="{{ user.avatar.url }}">{{ user.avatar.url }}</a><br />
                                修改：<input type="fiel" name="avatar" class="clearable-file-input" id="id_avatar" />
                            </div>
                        </div>
                        <button class="btn btn-info btn-sm rounded-0" type="submit">更新资料</button>
                    </form>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title"><span>更多操作</span></div>
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/accounts/profile/">查看资料</a>
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/">返回首页</a>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
</div>
</main>
{% endblock main %}

CloneBlog/templates/oauth/profile.html
{%extends 'account/base.html' %}
{% load staticfiles %}
{% load oauth_tags %}

{% block title %}
<title>个人中心</title>
{% endblock %}


<!--主要内容块-->
{% block main %}
<main>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card rounded-0 px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item text-center border-0" id="profile-avatar">
                        {% get_user_data request.session.uid as user %}
                            {% if user %}

                            <img class="avatar" src="{{ user.avatar.url }}" alt="{{user.username}}">

                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">用户名：</span>
                            <span>{{ user.username }}</span>
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">邮&emsp;箱：</span>
                            <span>{{ user.email }}</span>
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">网&emsp;址：</span>
                            <span>{{ user.link }}</span>
                        </li>
                    </ul>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/accounts/profile/change/">修改资料</a>
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/">返回首页</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</main>
{% endblock main %}