blogproject/blog/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('categories/<int:pk>/', views.category, name='category'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('tags/<int:pk>/', views.tags, name='tags'),
]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('', include('comments.urls')),
]

blogproject/comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('comment/<int:post_pk>/', views.comment, name='comment'),
]

blogproject/comments/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

class Comment(models.Model):
    name = models.CharField(max_length=50, verbose_name='名字')
    email = models.EmailField(verbose_name='邮箱')
    url = models.URLField(blank=True, verbose_name='网址')
    text = models.TextField(verbose_name='内容')
    created_time = models.DateTimeField(verbose_name='创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name='评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

blogproject/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from django.views.decorators.http import require_POST

from .form import CommentForm
from  django.contrib import messages
# Create your views here.

@require_POST
def comment(request, post_pk):
    ''' comment view handler '''
    post = get_object_or_404(Post, pk=post_pk)

    form = CommentForm(request.POST)

    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid() :
        commit = form.save(commit=False)

        commit.post = post

        commit.save()
        messages.add_message(request,messages.SUCCESS,'评论发表成功！', extra_tags='success')
        return redirect(post)

    context = {
        'post' : post,
        'form' : form,
    }
    messages.add_message(request,messages.ERROR,'评论发表失败，请修改错误后重新提交！', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

blogproject/comments/templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}</label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
        </div>
    </div>
</form>

blogproject/comments/templates/comments/inclusions/_list.html
<div class="comment-list-panel">
    <h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
    <ul class="comment-list list-unstyled">
        {% for comment in comment_list %}
        <li class="comment-item">
            <span class="nickname">{{ comment.name }}</span>
            <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
            <div class="text">
                {{ comment.text }}    
            </div>
        </li>
        {% empty %}
        暂无评论！
        {% endfor %}
    </ul>
</div>